services:

  db:
    image: postgres:18

    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-0000}
      POSTGRES_DB: ${DATABASE_NAME:-xala} 

    volumes:
      - dbvolume:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    image: ${DOCKER_USER_NAME:-ashenv2}/xala-backend:latest

    expose:
      - "8000"

    command: /bin/sh -c "alembic upgrade heads && fastapi run main.py"

    depends_on:
       db:
          condition: service_healthy
    
    environment:
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-0000}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_NAME: ${DATABASE_NAME:-xala}
      SECRET_KEY: "${SECRET_KEY:-4f1a9b2c8e3d7f0a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a}"
      ALGORITHM: "${ALGORITHM:-HS256}"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES:-60}"
      GEMINI_API_KEY: "${GEMINI_API_KEY:-defaultgeminiapikey}"
      MAIL_API_KEY: "${MAIL_API_KEY:-defaultmailapikey}"
      FRONTEND_URL: "${FRONTEND_URL:-http://localhost}"

  srvr:
    image: ${DOCKER_USER_NAME:-ashenv2}/xala-frontend:latest

    ports:
      - 80:80

    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost/api/}

    depends_on:
      - backend

volumes:
  dbvolume: