"""auto user-ai-request-count

Revision ID: 1a356ed5e0c8
Revises: 4c1aacf85800
Create Date: 2026-03-30 11:11:55.261977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a356ed5e0c8'
down_revision: Union[str, Sequence[str], None] = '4c1aacf85800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
