"""'cascade'

Revision ID: 3b0a4ff61f31
Revises: 15784c28f8fc
Create Date: 2026-03-21 10:26:11.623829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0a4ff61f31'
down_revision: Union[str, Sequence[str], None] = '15784c28f8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_cart_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'menu_items', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('carts_user_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('menu_items_menu_table_id_fkey'), 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'user_menus', ['menu_table_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key(op.f('menu_items_menu_table_id_fkey'), 'menu_items', 'user_menus', ['menu_table_id'], ['id'])
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_user_id_fkey'), 'carts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_cart_id_fkey'), 'cart_items', 'carts', ['cart_id'], ['id'])
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'menu_items', ['product_id'], ['id'])
    # ### end Alembic commands ###
